### ISSUE TITLE
[Css/Sass] Unwanted navigation bar overlapping 

### ISSUE THREAD

**Issue by developerasun** [developerasun/pawcon#161]
# issue : navigation bar overlapped below elements
## screenshot : attach a screenshot showing the bug
![navbar-overlapped](https://user-images.githubusercontent.com/83855174/159263955-20393d1c-8f57-4964-aac8-863b8fb21801.png)

**Comment by developerasun** [comment]
## solution : setting a wrapper div and set postion as relative. 

```css
        #menu {
            position: relative; // set wrapper div
            #lists::before {
                content: 'Logo here';
            }
            #lists { 
                display: flex;
                justify-content: space-around;
                cursor:auto;
                .listsItem {
                    flex-basis: content;
                }
            }
        }
```

## reference
- https://stackoverflow.com/questions/14553273/how-can-i-prevent-html-elements-from-overlapping-or-sliding-under-one-another
