### ISSUE TITLE
[Css/Sass] may not @extend selectors acroess media queries

### ISSUE THREAD

**Issue by developerasun** [developerasun/pawcon#163]
# issue : describe the bug shortly
## screenshot : attach a screenshot showing the bug
![no-extend-media-query](https://user-images.githubusercontent.com/83855174/159306697-309be209-2ad8-4bcb-a03b-de83e281da5a.png)

**Comment by developerasun** [comment]
## solution : use mixin instead of extend in media query like below.

```scss
@mixin imgGrid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    justify-content: center;
    align-items: center;
    margin-top: $unit;
    .texts {
        p {
            margin-top: $unit*2;
        }
    }
}

// tablet size
@media screen and (min-width: $tablet) {
    // tablet : image banner is forced to be a grid
    .imgVertical, .imgGrid { 
        @include imgGrid();
    }
}
```
